### PR TITLE
Minor proposal for readability of CI lines in the zipper plot

### PR DESCRIPTION
**Pull request by lorenzo-guizzaro**
Hi there,

while using this (great!) package, I have had some difficulties in seeing the CI lines of the zipper plot.

Thinking of changing their color to a more visible one, I have also thought to perhaps giving an option to make it clear whether there is optimal coverage or not. Please disregard if it does not make sense. In any case, thanks for making this package available!

### CODE REVIEW

**Comment by ellessenne** [comment]
Hi @lorenzo-guizzaro and thank you for this PR.

Could you paste some examples here to show the different looks under the `ci_colors` options, e.g., using {[reprex](https://reprex.tidyverse.org/)}?

Thanks!

**Comment by ellessenne** [comment]
Ok, looks good, thanks!

I have a few suggestion for the implementation:

- Would rename the argument to `zip_ci_colors` to highlight that it only applies to zip plots;

- Rather than having `ci_colors = 1,2,3` I would have the user pass colour hex codes. So:
  1. If the user passes one string with a hex code, that is used as the yellow is now (equivalent to `ci_colors = 1`);
  2. If the user passes a vector with two hex codes, that is used for _good/bad_ coverage scenarios (equivalent to `ci_colors = 2`);
  3. If the user passes a vector with three hex codes, that is used for _too low/ok/too high_ coverage scenarios (equivalent to `ci_colors = 3`). 
  
  Then, the default would be a single hex code (or color) `zip_ci_colors = "yellow"`, thus leading to exactly the same plots (=reproducible code, no breaking changes), while giving flexibility to the user to customise the plot.

What do you think about the above?

**Comment by lorenzo-guizzaro** [comment]
Thank you Alessandro, your ideas make much more sense and are best practice ;)

``` r
library(ggplot2)
#> Warning: package 'ggplot2' was built under R version 4.3.2
library(devtools)
#> Warning: package 'devtools' was built under R version 4.3.2
#> Loading required package: usethis
#> Warning: package 'usethis' was built under R version 4.3.2
load_all("../rsimsum/")
#> ℹ Loading rsimsum
#> Warning: package 'testthat' was built under R version 4.3.2

data("relhaz", package = "rsimsum")
s1 <- simsum(
  data = relhaz, estvarname = "theta", se = "se", true = -0.50,
  methodvar = "model", by = c("n", "baseline"), x = TRUE
)
#> 'ref' method was not specified, Cox set as the reference

autoplot(s1, zoom = .3, type = "zip", zip_ci_colors = c("green", "red", "blue"))
```



``` r
autoplot(s1, zoom = .3, type = "zip", zip_ci_colors = c("green", "red"))
```



``` r
autoplot(s1, zoom = .3, type = "zip", zip_ci_colors = c("yellow"))
```



``` r
autoplot(s1, zoom = .3, type = "zip")
```



<sup>Created on 2023-12-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ellessenne** [comment]
Looks good – thanks 👍 

Once the checks run I can merge this PR!

**Pull request merged**
